### ISSUE TITLE
bug per simone

### ISSUE THREAD

**Issue by ceribbo** [ClothAppProject/ClothAppAndroid#29]
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
                                                                  at java.util.ArrayList.get(ArrayList.java:310)
                                                                  at com.clothapp.profile.utils.ProfileUtils.updateShopListItem(ProfileUtils.java:347)
                                                                  at com.clothapp.profile.utils.ProfileUtils.access$200(ProfileUtils.java:41)
                                                                  at com.clothapp.profile.utils.ProfileUtils$5.done(ProfileUtils.java:265)
                                                                  at com.clothapp.profile.utils.ProfileUtils$5.done(ProfileUtils.java:257)
                                                                  at com.parse.ParseTaskUtils$2$1.run(ParseTaskUtils.java:116)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by c-simone** [comment]
Mi riesci a spiegare come riprodurre il bug?
