### ISSUE TITLE
New Bug

### ISSUE THREAD

**Issue by ceribbo** [ClothAppProject/ClothAppAndroid#31]
03-09 20:42:07.361 21932-21932/com.clothapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.clothapp, PID: 21932
                                                              java.lang.StringIndexOutOfBoundsException: length=1; regionStart=1; regionLength=1
                                                                  at java.lang.String.startEndAndLength(String.java:504)
                                                                  at java.lang.String.substring(String.java:1333)
                                                                  at com.clothapp.resources.Image.getHashtagToString(Image.java:116)
                                                                  at com.clothapp.ImageDetailFragment$3.done(ImageDetailFragment.java:193)
                                                                  at com.clothapp.ImageDetailFragment$3.done(ImageDetailFragment.java:168)

**Comment by c-simone** [comment]
Bug fixed. An empty hashtag would crash the app.
